### ISSUE TITLE
Cannot plot the results using plotGeneration.sh: subprocess raises child_exception

### ISSUE THREAD

**Issue by shangshang-wang** [timo-verstraeten/mats-experiments#3]
I ran this whole experiments in a Python 2 conda env (Python 2.7) on Ubuntu, namely, the command `python runExperiments.py experments/experiments.json` in the `mats-experiments/cpp/plots/` folder. Then in the same folder, I ran the command `bash plotGeneration.sh` and encountered the problem as following:

```
['/home/updrew/Desktop/mamab/coordination/mats-experiments/cpp/plots/Scripts/makeGnuplotScript.sh', '/home/updrew/Desktop/mamab/coordination/mats-experiments/cpp/plots/./experiments/plots/nodes.png', 'na', '2500', '50', '', 'thompsonb', 'mats ', '1', 'mauce', 'mauce ', '1', 'rnd', 'rnd ', '1']
set output '/home/updrew/Desktop/mamab/coordination/mats-experiments/cpp/plots/./experiments/plots/nodes.png'
set terminal pngcairo size 1200,900 linewidth 7 rounded
set key font ",20"
set xtics font ", 24"
set ytics font ", 24"
set lmargin 15
set rmargin 6
set tmargin 3
set bmargin 5
set dashtype 2 (30,30)
set dashtype 12 (9,9)
set dashtype 3 (7,15)
set dashtype 13 (4,7)
set dashtype 4 (30,15,10,15)
set dashtype 14 (15,7,5,7)
set dashtype 5 (30,15,5,15,5,15)
set dashtype 15 (10,6,2,6,2,5)
set dashtype 7 (30,30)
set dashtype 17 (9,9)
set dashtype 8 (7,15)
set dashtype 18 (4,7)
set dashtype 9 (30,15,10,15)
set dashtype 19 (15,7,5,7)
set dashtype 10 (30,15,5,15,5,15)
set dashtype 20 (10,6,2,6,2,5)
set key reverse Left left top samplen 2.25 box opaque width 1
set xtics 2500
set xrange [0<*:]
set yrange [0:50]
set style fill transparent solid 0.4 noborder
set colorsequence podo
set datafile missing NaN
set title ""
plot 'thompsonb' using 1:3 with line smooth csplines ls 1 dt 1 notitle, \
   NaN with line title 'mats ' ls 1 dt 11 lw 1, \
   'thompsonb' using 1 : ($3-$5) : ($3+$5) with filledcurves ls 1 notitle, \
   'mauce' using 1:3 with line smooth csplines ls 2 dt 2 notitle, \
   NaN with line title 'mauce ' ls 2 dt 12 lw 1, \
   'mauce' using 1 : ($3-$5) : ($3+$5) with filledcurves ls 2 notitle, \
   'rnd' using 1:3 with line smooth csplines ls 3 dt 3 notitle, \
   NaN with line title 'rnd ' ls 3 dt 13 lw 1, \
   'rnd' using 1 : ($3-$5) : ($3+$5) with filledcurves ls 3 notitle

Traceback (most recent call last):
  File "./Scripts/plotResults.py", line 258, in <module>
    subprocess.call(["gnuplot","-p","plot"], cwd=plotTmpDir)
  File "/home/updrew/anaconda3/envs/mamab27/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/updrew/anaconda3/envs/mamab27/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/updrew/anaconda3/envs/mamab27/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Missing folder for method mauce; skipping...
Missing folder for method rnd; skipping...
Missing folder for method thompsonp; skipping...
No files match the specified options
Missing folder for method mauce; skipping...
Missing folder for method rnd; skipping...
Missing folder for method thompsonb; skipping...
No files match the specified options
No files match the specified options
No files match the specified options
Missing folder for method mauce; skipping...
No files match the specified options
```
Just in case, I also went to the folder `mats-experiments/cpp/plots/experiments/results` to check if I had all the results (command `tree /results)`

```
.
├── mines
│   ├── llr
│   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   ├── experiments=100_seed=1_timesteps=40000
│   │   ├── experiments=100_seed=2_timesteps=40000
│   │   ├── experiments=100_seed=3_timesteps=40000
│   │   ├── logs
│   │   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   │   ├── experiments=100_seed=1_timesteps=40000
│   │   │   ├── experiments=100_seed=2_timesteps=40000
│   │   │   └── experiments=100_seed=3_timesteps=40000
│   │   └── statistics
│   │       ├── experiments=100_seed=10000_timesteps=40000
│   │       ├── experiments=100_seed=1000_timesteps=40000
│   │       ├── experiments=100_seed=1_timesteps=40000
│   │       ├── experiments=100_seed=2_timesteps=40000
│   │       └── experiments=100_seed=3_timesteps=40000
│   ├── mauce
│   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   ├── experiments=100_seed=1_timesteps=40000
│   │   ├── experiments=100_seed=2_timesteps=40000
│   │   ├── experiments=100_seed=3_timesteps=40000
│   │   ├── logs
│   │   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   │   ├── experiments=100_seed=1_timesteps=40000
│   │   │   ├── experiments=100_seed=2_timesteps=40000
│   │   │   └── experiments=100_seed=3_timesteps=40000
│   │   └── statistics
│   │       ├── experiments=100_seed=10000_timesteps=40000
│   │       ├── experiments=100_seed=1000_timesteps=40000
│   │       ├── experiments=100_seed=1_timesteps=40000
│   │       ├── experiments=100_seed=2_timesteps=40000
│   │       └── experiments=100_seed=3_timesteps=40000
│   ├── rnd
│   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   ├── experiments=100_seed=1_timesteps=40000
│   │   ├── experiments=100_seed=2_timesteps=40000
│   │   ├── experiments=100_seed=3_timesteps=40000
│   │   ├── logs
│   │   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   │   ├── experiments=100_seed=1_timesteps=40000
│   │   │   ├── experiments=100_seed=2_timesteps=40000
│   │   │   └── experiments=100_seed=3_timesteps=40000
│   │   └── statistics
│   │       ├── experiments=100_seed=10000_timesteps=40000
│   │       ├── experiments=100_seed=1000_timesteps=40000
│   │       ├── experiments=100_seed=1_timesteps=40000
│   │       ├── experiments=100_seed=2_timesteps=40000
│   │       └── experiments=100_seed=3_timesteps=40000
│   ├── scql
│   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   ├── experiments=100_seed=1_timesteps=40000
│   │   ├── experiments=100_seed=2_timesteps=40000
│   │   ├── experiments=100_seed=3_timesteps=40000
│   │   ├── logs
│   │   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   │   ├── experiments=100_seed=1_timesteps=40000
│   │   │   ├── experiments=100_seed=2_timesteps=40000
│   │   │   └── experiments=100_seed=3_timesteps=40000
│   │   └── statistics
│   │       ├── experiments=100_seed=10000_timesteps=40000
│   │       ├── experiments=100_seed=1000_timesteps=40000
│   │       ├── experiments=100_seed=1_timesteps=40000
│   │       ├── experiments=100_seed=2_timesteps=40000
│   │       └── experiments=100_seed=3_timesteps=40000
│   ├── thompson
│   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   ├── experiments=100_seed=1_timesteps=40000
│   │   ├── experiments=100_seed=2_timesteps=40000
│   │   ├── experiments=100_seed=3_timesteps=40000
│   │   ├── logs
│   │   │   ├── experiments=100_seed=10000_timesteps=40000
│   │   │   ├── experiments=100_seed=1000_timesteps=40000
│   │   │   ├── experiments=100_seed=1_timesteps=40000
│   │   │   ├── experiments=100_seed=2_timesteps=40000
│   │   │   └── experiments=100_seed=3_timesteps=40000
│   │   └── statistics
│   │       ├── experiments=100_seed=10000_timesteps=40000
│   │       ├── experiments=100_seed=1000_timesteps=40000
│   │       ├── experiments=100_seed=1_timesteps=40000
│   │       ├── experiments=100_seed=2_timesteps=40000
│   │       └── experiments=100_seed=3_timesteps=40000
│   └── thompsonb
│       ├── experiments=100_seed=10000_timesteps=40000
│       ├── experiments=100_seed=1000_timesteps=40000
│       ├── experiments=100_seed=1_timesteps=40000
│       ├── experiments=100_seed=2_timesteps=40000
│       ├── experiments=100_seed=3_timesteps=40000
│       ├── logs
│       │   ├── experiments=100_seed=10000_timesteps=40000
│       │   ├── experiments=100_seed=1000_timesteps=40000
│       │   ├── experiments=100_seed=1_timesteps=40000
│       │   ├── experiments=100_seed=2_timesteps=40000
│       │   └── experiments=100_seed=3_timesteps=40000
│       └── statistics
│           ├── experiments=100_seed=10000_timesteps=40000
│           ├── experiments=100_seed=1000_timesteps=40000
│           ├── experiments=100_seed=1_timesteps=40000
│           ├── experiments=100_seed=2_timesteps=40000
│           └── experiments=100_seed=3_timesteps=40000
├── nodes
│   ├── llr
│   │   ├── experiments=100_nodes=10_timesteps=10000
│   │   ├── logs
│   │   │   └── experiments=100_nodes=10_timesteps=10000
│   │   └── statistics
│   │       └── experiments=100_nodes=10_timesteps=10000
│   ├── mauce
│   │   ├── experiments=100_nodes=10_timesteps=10000
│   │   ├── logs
│   │   │   └── experiments=100_nodes=10_timesteps=10000
│   │   └── statistics
│   │       └── experiments=100_nodes=10_timesteps=10000
│   ├── rnd
│   │   ├── experiments=100_nodes=10_timesteps=10000
│   │   ├── logs
│   │   │   └── experiments=100_nodes=10_timesteps=10000
│   │   └── statistics
│   │       └── experiments=100_nodes=10_timesteps=10000
│   ├── scql
│   │   ├── experiments=100_nodes=10_timesteps=10000
│   │   ├── logs
│   │   │   └── experiments=100_nodes=10_timesteps=10000
│   │   └── statistics
│   │       └── experiments=100_nodes=10_timesteps=10000
│   ├── thompson
│   │   ├── experiments=100_nodes=10_timesteps=10000
│   │   ├── logs
│   │   │   └── experiments=100_nodes=10_timesteps=10000
│   │   └── statistics
│   │       └── experiments=100_nodes=10_timesteps=10000
│   └── thompsonb
│       ├── experiments=100_nodes=10_timesteps=10000
│       ├── logs
│       │   └── experiments=100_nodes=10_timesteps=10000
│       └── statistics
│           └── experiments=100_nodes=10_timesteps=10000
└── wind
    ├── llr
    │   ├── logs
    │   │   └── experiments=1_timesteps=2000
    │   └── statistics
    │       └── experiments=1_timesteps=2000
    ├── mauce
    │   ├── logs
    │   │   └── experiments=1_range=0.03_timesteps=2000
    │   └── statistics
    │       └── experiments=1_range=0.03_timesteps=2000
    ├── rnd
    │   ├── logs
    │   │   └── experiments=1_seed=1_timesteps=2000
    │   └── statistics
    │       └── experiments=1_seed=1_timesteps=2000
    ├── scql
    │   ├── logs
    │   │   ├── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=10000
    │   │   ├── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=20000
    │   │   └── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=60000
    │   └── statistics
    │       ├── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=10000
    │       ├── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=20000
    │       └── epsilon=0.1_experiments=1_timesteps=2000_zeroeps=60000
    └── thompson
        ├── logs
        │   └── experiments=1_timesteps=2000
        └── statistics
            └── experiments=1_timesteps=2000

54 directories, 122 files

```

**Comment by Svalorzen** [comment]
I'm not sure to be honest. Do you have gnuplot installed on your system? Does it work?

**Comment by shangshang-wang** [comment]
Yes and no. There are finally some outputs, but still, not all problems solved. I will keep trying on it later.

**Comment by Svalorzen** [comment]
Well, the output files are simply files in the form of

`timestep avg_immediate_reward avg_cumulative_reward immediate_std cumulative_std`

So if you feel like plotting them in some other way feel free to do so. The scripts are just there to make life easier but if they don't work you don't have to use them.

**Comment by shangshang-wang** [comment]
Ok, thanks for the information.

**Comment by shangshang-wang** [comment]
All the figures are created except the wind experiment related ones. In the README file from the `sim` folder, it seems so strange that I should somewhat "create a virtual env (Python 3) inside a virtual env (Python 2)". After the line 9, I am told to create another python 3 env. However, should I `deactivate` from the current Python 2.7 virtual env first ? Or, directly create another inside it, it does not make sense to me ... 

```
1. Go to the main folder directory
2. Create a Python 2.7 venv situated in the sim folder
3. virtualenv ./sim/
4. Go inside the sim folder
5. Activate the venv
6. source ./bin/activate
7. From the venv, run the go-openmdao-0.13.0.py
8. Install any additional required packages
9. pip install matplotlib
10. Go to the main folder directory
11. Create a Python 3 venv situated in the sim folder
12. python3 -m venv ./sim/
13. Go inside the sim folder
14. Activate the venv
15. source ./bin/activate
16. Install any additional required packages
17. pip install matplotlib scipy
```
